runtime: php
env: flex

runtime_config:
  document_root: public

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:YOUR_APP_KEY
  STORAGE_DIR: /tmp
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  REDIS_HOST: "<Cloud_Memorystore_Instance_IP>"  # Ensure this is a string
  REDIS_PASSWORD: null  # 'null' is correctly interpreted as a null value
  REDIS_PORT: "<Cloud_Memorystore_Port>"        # Ensure this is a string
  DB_CONNECTION: mysql
  DB_HOST: "<Cloud_SQL_Instance_IP>"            # Ensure this is a string
  DB_PORT: "3306"                               # Ensure this is a string
  DB_DATABASE: "<Cloud_SQL_Database_Name>"      # Ensure this is a string
  DB_USERNAME: "<Cloud_SQL_Username>"           # Ensure this is a string
  DB_PASSWORD: "<Cloud_SQL_Password>"           # Ensure this is a string
