version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: .docker/php-fpm/Dockerfile
    image: simple-secure-host-auth-gateway
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network

  nginx:
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: <Cloud_SQL_Database_Name>
      MYSQL_ROOT_PASSWORD: <Cloud_SQL_Password>
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local