version: '1'
services:
  php-fpm:
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: .docker/php-fpm/Dockerfile.dockerfile
    command: /bin/bash -c "composer install && npm ci && npm run dev && php artisan migrate"
    image: tylertheliger/sshag-php-fpm
    container_name: app #important for app-network
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network

  nginx:
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile.dockerfile
      args:
        CACHEBUST: 1
    image: tylertheliger/sshag-nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local